"""Wrapper skeleton for the Xilinx FFT IP (black box).

Instantiates the IP generated by ip/gen_fft_ip.tcl as an Amaranth `Instance`
and exposes its AXI-Stream interfaces with the complex payload packed/unpacked
the way the IP expects (each component sign-extended to a byte-aligned field,
real in the low half, imag in the high half).

This is the synthesis path only -- the IP cannot run in pysim. For simulation
the FFT is substituted by the model's BFP FFT (see guider_hdl.cosim); the IP
itself is verified in Vivado xsim against the model, tolerance-based.

The transform itself is verified: sim/fft_cosim.py drives this exact IP config in
Vivado xsim and matches a numpy DFT to ~1e-5 (see that module). The streaming core
frames at a fixed phase offset from the input tlast (captured frame == DFT of a +1
cyclic shift); that offset is a *common* cyclic shift and cancels in the
cross-power conj(F_ref)*F_img, so it is benign for the guider. The synthesizable
top-level still owns explicit framing.

This module is the bare IP port map + payload packing. The framing around it --
config word (FWD/INV), per-row tlast, output reframing, tuser->block-exponent,
and backpressure -- lives in fft_pass.FftPass, which drives this `core` (or the
behavioral FftStub below in pysim). NB on tlast: the core's frame phase is fixed
relative to it, not steered by it; rely on the common-rotation cancellation
above rather than chasing a tlast alignment.
"""
from __future__ import annotations
from amaranth import *


def _field_width(width: int) -> int:
    """IP pads each complex component up to a byte boundary."""
    return (width + 7) // 8 * 8


class FftIP(Elaboratable):
    def __init__(self, n: int = 256, input_width: int = 18,
                 output_width: int | None = None, phase_width: int = 16):
        self.n = n
        self.input_width = input_width
        self.output_width = output_width or input_width   # BFP keeps mantissa width
        self.phase_width = phase_width
        self.module_name = f"fft_{n}"

        icw = _field_width(input_width)
        ocw = _field_width(self.output_width)
        # config word: FWD/INV (+ per-stage scaling for non-BFP, unused here)
        self.cfg_width = 8

        # --- slave config channel ---
        self.s_cfg_tdata = Signal(self.cfg_width)
        self.s_cfg_tvalid = Signal()
        self.s_cfg_tready = Signal()
        # --- slave data channel (input samples) ---
        self.s_re = Signal(signed(input_width))
        self.s_im = Signal(signed(input_width))
        self.s_tvalid = Signal()
        self.s_tlast = Signal()
        self.s_tready = Signal()
        # --- master data channel (transform output) ---
        self.m_re = Signal(signed(self.output_width))
        self.m_im = Signal(signed(self.output_width))
        self.m_tvalid = Signal()
        self.m_tlast = Signal()
        self.m_tready = Signal()
        self.m_blk_exp = Signal(8)        # from m_axis_data_tuser (BFP exponent)
        # status channel: unused under BFP (block exponent rides on tuser); its
        # tready is tied high so the IP never stalls waiting on it.
        self.m_status_tdata = Signal(8)
        self.m_status_tvalid = Signal()

        self._icw, self._ocw = icw, ocw

    def elaborate(self, platform):
        m = Module()
        icw, ocw = self._icw, self._ocw

        s_tdata = Signal(2 * icw)
        m_tdata = Signal(2 * ocw)
        m_tuser = Signal(24)
        # pack: real low, imag high, each sign-extended to a byte-aligned field
        re_f, im_f = Signal(icw), Signal(icw)
        m.d.comb += [re_f.eq(self.s_re), im_f.eq(self.s_im),
                     s_tdata.eq(Cat(re_f, im_f))]
        # unpack output + block exponent
        m.d.comb += [
            self.m_re.eq(m_tdata[:ocw][:self.output_width].as_signed()),
            self.m_im.eq(m_tdata[ocw:][:self.output_width].as_signed()),
            self.m_blk_exp.eq(m_tuser[:8]),
        ]

        m.submodules.ip = Instance(
            self.module_name,
            i_aclk=ClockSignal("sync"),
            i_aresetn=~ResetSignal("sync"),
            i_s_axis_config_tdata=self.s_cfg_tdata,
            i_s_axis_config_tvalid=self.s_cfg_tvalid,
            o_s_axis_config_tready=self.s_cfg_tready,
            i_s_axis_data_tdata=s_tdata,
            i_s_axis_data_tvalid=self.s_tvalid,
            i_s_axis_data_tlast=self.s_tlast,
            o_s_axis_data_tready=self.s_tready,
            o_m_axis_data_tdata=m_tdata,
            o_m_axis_data_tuser=m_tuser,
            o_m_axis_data_tvalid=self.m_tvalid,
            o_m_axis_data_tlast=self.m_tlast,
            i_m_axis_data_tready=self.m_tready,
            o_m_axis_status_tdata=self.m_status_tdata,
            o_m_axis_status_tvalid=self.m_status_tvalid,
            i_m_axis_status_tready=Const(1),
        )
        return m


class FftStub(Elaboratable):
    """Sim-only behavioral stand-in for FftIP, same AXI-S port surface.

    Does NOT transform -- it is an identity 1-deep skid that mimics the IP's
    streaming protocol (VALID/READY handshake, per-frame TLAST passthrough, a
    TUSER block exponent) so the FftPass framing/config/backpressure logic can be
    exercised in pysim. The transform itself is verified separately against the
    real IP in Vivado xsim (sim/fft_cosim.py). Inject it via FftPass(core=...).
    """

    def __init__(self, n: int = 256, input_width: int = 18,
                 output_width: int | None = None, phase_width: int = 16,
                 blk_exp: int = 0):
        self.n = n
        self.input_width = input_width
        self.output_width = output_width or input_width
        self.blk_exp = blk_exp
        ow = self.output_width
        self.s_cfg_tdata = Signal(8)
        self.s_cfg_tvalid = Signal()
        self.s_cfg_tready = Signal()
        self.s_re = Signal(signed(input_width))
        self.s_im = Signal(signed(input_width))
        self.s_tvalid = Signal()
        self.s_tlast = Signal()
        self.s_tready = Signal()
        self.m_re = Signal(signed(ow))
        self.m_im = Signal(signed(ow))
        self.m_tvalid = Signal()
        self.m_tlast = Signal()
        self.m_tready = Signal()
        self.m_blk_exp = Signal(8)

    def elaborate(self, platform):
        m = Module()
        valid = Signal()
        re_r = Signal(signed(self.output_width))
        im_r = Signal(signed(self.output_width))
        last_r = Signal()
        m.d.comb += [
            self.s_cfg_tready.eq(1),
            self.s_tready.eq(self.m_tready | ~valid),   # accept if sink ready or empty
            self.m_tvalid.eq(valid),
            self.m_re.eq(re_r), self.m_im.eq(im_r),
            self.m_tlast.eq(last_r),
            self.m_blk_exp.eq(self.blk_exp),
        ]
        accept = self.s_tvalid & self.s_tready
        with m.If(accept):
            m.d.sync += [valid.eq(1), re_r.eq(self.s_re), im_r.eq(self.s_im),
                         last_r.eq(self.s_tlast)]
        with m.Elif(self.m_tvalid & self.m_tready):
            m.d.sync += valid.eq(0)
        return m
