"""Wrapper skeleton for the Xilinx FFT IP (black box).

Instantiates the IP generated by ip/gen_fft_ip.tcl as an Amaranth `Instance`
and exposes its AXI-Stream interfaces with the complex payload packed/unpacked
the way the IP expects (each component sign-extended to a byte-aligned field,
real in the low half, imag in the high half).

This is the synthesis path only -- the IP cannot run in pysim. For simulation
the FFT is substituted by the model's BFP FFT (see guider_hdl.cosim); the IP
itself is verified in Vivado xsim against the model, tolerance-based.

STATUS: skeleton. Port map + payload packing are in place. Still TODO for the
synthesizable top-level:
  * s_axis_config framing: build the config word (FWD/INV bit, scaling sched)
    and drive s_axis_config_tvalid once per frame.
  * tlast generation on the input stream (last sample of each N-point frame).
  * route m_axis_data_tuser -> BFP block exponent and accumulate it across the
    row/column passes (mirrors the model's per-pass exponent tracking).
  * backpressure: honor s_axis_data_tready / drive m_axis_data_tready.
"""
from __future__ import annotations
from amaranth import *


def _field_width(width: int) -> int:
    """IP pads each complex component up to a byte boundary."""
    return (width + 7) // 8 * 8


class FftIP(Elaboratable):
    def __init__(self, n: int = 256, input_width: int = 18,
                 output_width: int | None = None, phase_width: int = 16):
        self.n = n
        self.input_width = input_width
        self.output_width = output_width or input_width   # BFP keeps mantissa width
        self.phase_width = phase_width
        self.module_name = f"fft_{n}"

        icw = _field_width(input_width)
        ocw = _field_width(self.output_width)
        # config word: FWD/INV (+ per-stage scaling for non-BFP, unused here)
        self.cfg_width = 8

        # --- slave config channel ---
        self.s_cfg_tdata = Signal(self.cfg_width)
        self.s_cfg_tvalid = Signal()
        self.s_cfg_tready = Signal()
        # --- slave data channel (input samples) ---
        self.s_re = Signal(signed(input_width))
        self.s_im = Signal(signed(input_width))
        self.s_tvalid = Signal()
        self.s_tlast = Signal()
        self.s_tready = Signal()
        # --- master data channel (transform output) ---
        self.m_re = Signal(signed(self.output_width))
        self.m_im = Signal(signed(self.output_width))
        self.m_tvalid = Signal()
        self.m_tlast = Signal()
        self.m_tready = Signal()
        self.m_blk_exp = Signal(8)        # from m_axis_data_tuser (BFP exponent)
        # status channel: unused under BFP (block exponent rides on tuser); its
        # tready is tied high so the IP never stalls waiting on it.
        self.m_status_tdata = Signal(8)
        self.m_status_tvalid = Signal()

        self._icw, self._ocw = icw, ocw

    def elaborate(self, platform):
        m = Module()
        icw, ocw = self._icw, self._ocw

        s_tdata = Signal(2 * icw)
        m_tdata = Signal(2 * ocw)
        m_tuser = Signal(24)
        # pack: real low, imag high, each sign-extended to a byte-aligned field
        re_f, im_f = Signal(icw), Signal(icw)
        m.d.comb += [re_f.eq(self.s_re), im_f.eq(self.s_im),
                     s_tdata.eq(Cat(re_f, im_f))]
        # unpack output + block exponent
        m.d.comb += [
            self.m_re.eq(m_tdata[:ocw][:self.output_width].as_signed()),
            self.m_im.eq(m_tdata[ocw:][:self.output_width].as_signed()),
            self.m_blk_exp.eq(m_tuser[:8]),
        ]

        m.submodules.ip = Instance(
            self.module_name,
            i_aclk=ClockSignal("sync"),
            i_aresetn=~ResetSignal("sync"),
            i_s_axis_config_tdata=self.s_cfg_tdata,
            i_s_axis_config_tvalid=self.s_cfg_tvalid,
            o_s_axis_config_tready=self.s_cfg_tready,
            i_s_axis_data_tdata=s_tdata,
            i_s_axis_data_tvalid=self.s_tvalid,
            i_s_axis_data_tlast=self.s_tlast,
            o_s_axis_data_tready=self.s_tready,
            o_m_axis_data_tdata=m_tdata,
            o_m_axis_data_tuser=m_tuser,
            o_m_axis_data_tvalid=self.m_tvalid,
            o_m_axis_data_tlast=self.m_tlast,
            i_m_axis_data_tready=self.m_tready,
            o_m_axis_status_tdata=self.m_status_tdata,
            o_m_axis_status_tvalid=self.m_status_tvalid,
            i_m_axis_status_tready=Const(1),
        )
        return m
