// StaleAbsorber: drops the first skip_n beats from the AXIS switch output.
//
// The Xilinx AXIS switch in ROUTING_MODE=1 uses a registered pipeline whose
// SRL content is NOT flushed by aresetn.  After each frame, the final 2-4
// beats remain in the pipeline and appear as a stale prefix on the next frame.
// The absorber silently consumes those prefix beats (asserting S_AXIS_TREADY
// but suppressing M_AXIS_TVALID) before the DMA sees them.
//
// skip_n is loaded from the CSR CTRL[10:7] field.  Software writes skip_n
// before each DMA kick; load is a 1-cycle pulse generated by the CSR one
// clock after the CTRL write (after skip_n has been registered).
// Same-slave transitions: skip_n=2; different-slave: skip_n=4.
//
// Vivado interface inference: S_AXIS_T* / M_AXIS_T* naming triggers automatic
// AXI4-Stream interface creation in the block design, allowing interface-level
// connections to sw_out/M00_AXIS and dma0/S_AXIS_S2MM.
`timescale 1ns/1ps
module stale_absorber #(
    parameter DATA_W = 128
) (
    input  wire              aclk,
    input  wire              aresetn,
    // control from CSR
    input  wire [3:0]        skip_n,
    input  wire              load,
    // AXI4-Stream slave (from sw_out M00_AXIS)
    input  wire              S_AXIS_TVALID,
    output wire              S_AXIS_TREADY,
    input  wire [DATA_W-1:0] S_AXIS_TDATA,
    input  wire              S_AXIS_TLAST,
    // AXI4-Stream master (to dma0 S_AXIS_S2MM)
    output wire              M_AXIS_TVALID,
    input  wire              M_AXIS_TREADY,
    output wire [DATA_W-1:0] M_AXIS_TDATA,
    output wire              M_AXIS_TLAST
);
    reg [3:0] cnt;
    wire passing = (cnt == 4'd0);

    always @(posedge aclk) begin
        if (!aresetn)
            cnt <= 4'd0;
        else if (load)
            cnt <= skip_n;
        else if (!passing && S_AXIS_TVALID)
            cnt <= cnt - 4'd1;
    end

    // When absorbing: drain s_axis (tready=1), suppress m_axis (tvalid=0).
    // When passing: full flow control pass-through.
    assign S_AXIS_TREADY = passing ? M_AXIS_TREADY : 1'b1;
    assign M_AXIS_TVALID = passing & S_AXIS_TVALID;
    assign M_AXIS_TDATA  = S_AXIS_TDATA;
    assign M_AXIS_TLAST  = S_AXIS_TLAST;
endmodule
